---
# tasks file for deploy_nginx
    - name: Install Epel Repo package from standart Repo
      yum:
        name: epel-release
        state: latest
      tags:
        -epel-package
        -packages

    - name: Install Nginx package from EPEL Repo
      yum:
        name: nginx
        state: latest
      tags:
        -nginx-package
        -packages

    - name: Nginx make config from template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        -nginx-config